apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 23.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/cilium
      targetRevision: 23.0.0
      helm:
        valueFiles:
          - $values/k8s/metal3/argocd-apps/values-cilium.yaml
    - repoURL: https://github.com/sbdtu5498/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - kind: Secret
      name: cilium-ca
      jsonPointers:
        - /data
    - kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data
    - kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data
