apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 23.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/sealed-secrets
      targetRevision: 23.0.0
      helm:
        valueFiles:
          - $values/k8s/metal3/argocd-apps/values-sealed-secrets.yaml
    - repoURL: https://github.com/sbdtu5498/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
